# -*- coding: utf-8 -*-
"""Manglish_SentimentClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbgz46yFmaX00oLpoEa8v4ofOicP2Weg
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import sys
import numpy as np
import os
import csv
import string
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from keras import regularizers
from numpy import array
from numpy import asarray
from numpy import zeros

df = pd.read_csv('/content/drive/MyDrive/PHD_Corpus/Blanced_CM.csv',  sep=',',usecols=[0, 1])
df

df_ub = pd.read_csv('/content/drive/MyDrive/PHD_Corpus/cm_unbalanced.csv',  sep=',',usecols=[0, 1])
df_ub

text=df['Review_Text']
text_ub=df_ub['Review_Text']

!pip install nltk
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

def count_sentences_in_column(dataframe, column_name):
    total_sentences = 0
    for text in dataframe[column_name]:
        sentences = nltk.sent_tokenize(text)
        total_sentences += len(sentences)
    return total_sentences

column_name = 'Review_Text'  # Replace this with the actual column name in your DataFrame
sentence_count = count_sentences_in_column(df, column_name)
print(f"Total number of sentences in column '{column_name}': {sentence_count}")
print("******************************************************")
print("Unbalanced Corpus Details")
sentence_count = count_sentences_in_column(df_ub, column_name)
print(f"Total number of sentences in column '{column_name}': {sentence_count}")


def count_words_in_column(dataframe, column_name):
    total_words = 0
    for text in dataframe[column_name]:
        words = text.split()  # Splitting text into words
        total_words += len(words)
    return total_words

column_name = 'Review_Text'  # Replace this with the actual column name in your DataFrame
word_count = count_words_in_column(df, column_name)
print(f"Total number of words in column '{column_name}': {word_count}")
print("******************************************************")
print("Unbalanced Corpus Details")
word_count = count_words_in_column(df_ub, column_name)
print(f"Total number of words in column '{column_name}': {word_count}")

def count_unique_words_in_column(dataframe, column_name):
    unique_words = set()  # Set to store unique words
    for text in dataframe[column_name]:
        words = text.split()  # Splitting text into words
        unique_words.update(words)  # Adding words to the set

    return len(unique_words)

column_name = 'Review_Text'  # Replace this with the actual column name in your DataFrame
unique_word_count = count_unique_words_in_column(df, column_name)
print(f"Total number of unique words in column '{column_name}': {unique_word_count}")
print("******************************************************")
print("Unbalanced Corpus Details")
unique_word_count = count_unique_words_in_column(df_ub, column_name)
print(f"Total number of unique words in column '{column_name}': {unique_word_count}")

def find_longest_sentence(dataframe, column_name):
    longest_sentence = ''
    max_word_count = 0

    for text in dataframe[column_name]:
        sentences = text.split('.')  # Splitting text into sentences
        for sentence in sentences:
            words = sentence.split()  # Splitting sentence into words
            word_count = len(words)
            if word_count > max_word_count:
                max_word_count = word_count
                longest_sentence = sentence.strip()  # Removing extra spaces

    return longest_sentence, max_word_count

column_name = 'Review_Text'  # Replace this with the actual column name in your DataFrame
longest_sentence, word_count = find_longest_sentence(df, column_name)
print(f"Longest sentence in column '{column_name}':")
print(longest_sentence)
print(f"Number of words in the longest sentence: {word_count}")
print("******************************************************")
print("Unbalanced Corpus Details")
longest_sentence, word_count = find_longest_sentence(df_ub, column_name)
print(f"Longest sentence in column '{column_name}':")
print(longest_sentence)

def calculate_average_sentence_length(dataframe, column_name):
    total_sentences = 0
    total_words = 0

    for text in dataframe[column_name]:
        sentences = nltk.sent_tokenize(text)
        total_sentences += len(sentences)
        for sentence in sentences:
            words = nltk.word_tokenize(sentence)
            total_words += len(words)

    if total_sentences == 0:  # To handle the case where there are no sentences
        return 0

    average_sentence_length = total_words / total_sentences
    return average_sentence_length

column_name = 'Review_Text'  # Replace this with the actual column name in your DataFrame
avg_sentence_length = calculate_average_sentence_length(df, column_name)
print(f"Average sentence length in column '{column_name}': {avg_sentence_length:.2f} words")
print("******************************************************")
print("Unbalanced Corpus Details")
avg_sentence_length = calculate_average_sentence_length(df_ub, column_name)
print(f"Average sentence length in column '{column_name}': {avg_sentence_length:.2f} words")

# Strip leading and trailing spaces from column names
df.columns = df.columns.str.strip()
# Now extract unique values
labels = df['Sentiment_Class']
# print(labels)

# Strip leading and trailing spaces from column names
df_ub.columns = df_ub.columns.str.strip()
# Now extract unique values
labels_ub = df_ub['Sentiment_Class']
print(labels_ub)

### LABEL DISTRIBUTION ###

df.Sentiment_Class.value_counts().plot.pie(figsize=(6,6))

# Assuming labels is a NumPy array
labels_series = pd.Series(labels)
# Now you can use value_counts
labels_count = labels_series.value_counts()
print(labels_count)

# Assuming labels is a NumPy array
labels_series_ub = pd.Series(labels_ub)
# Now you can use value_counts
labels_count_ub = labels_series_ub.value_counts()
print(labels_count_ub)

!pip install beautifulsoup4

import nltk, string, re, spacy,unicodedata, random
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import ToktokTokenizer
from bs4 import BeautifulSoup

# Data preprocessing function
def preprocess_text(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r"http\S+", "", text, flags=re.MULTILINE)
    text = re.sub(r"www\S+", "", text, flags=re.MULTILINE)
    text = re.sub(r"&\S+", "", text, flags=re.MULTILINE)
    text = re.sub(r"\.{2,}", ".", text, flags=re.MULTILINE)
    text = re.sub(r"&", " and ", text)

    text = text.replace("\n", ".")
    text = text.replace("&amp", " ")
    text = text.replace("-", "")
    text = text.replace(";", "")
    text = text.replace("@", "")
    text = text.replace('[{}]'.format(string.punctuation), '')
    punctuation = '!!"$%&()*+-/:;<=>?[\\]^_{|}~.'
    text = ''.join(ch for ch in text if ch not in set(punctuation))
    text = BeautifulSoup(text, 'html.parser').get_text()
    tokenizer = ToktokTokenizer()
    tokens = tokenizer.tokenize(text)
    text = ' '.join(tokens)
    return text



def process_data(df):
    df["Review_Text"] = df["Review_Text"].map(lambda x: preprocess_text(x))
    return df
df = process_data(df)
# Drop NA values
df = df.dropna()
# Define a function to load data
def load_data(dataframe):
    texts = dataframe['Review_Text'].tolist()
    labels = dataframe['Sentiment_Class'].tolist()  # Assuming 'category' column contains labels
    return texts, labels
data, label = load_data(df)

# *******************************************************************

def process_data(df):
    df_ub["Review_Text"] = df_ub["Review_Text"].map(lambda x: preprocess_text(x))
    return df_ub
df_ub = process_data(df_ub)
# Drop NA values
df_ub = df_ub.dropna()
# # Define a function to load data
# def load_data(dataframe):
#     texts = dataframe['Review_Text'].tolist()
#     labels = dataframe['Sentiment_Class'].tolist()  # Assuming 'category' column contains labels
#     return texts, labels
data_ub, label_ub = load_data(df_ub)
#

# Define a function to clean the code-mixed text while preserving the order
def clean_code_mixed_text(text):
    cleaned_text = ""
    current_language = None
    current_segment = ""
    # Iterate through each character in the input text
    for char in text:
        if re.match(r'[a-zA-Z]', char):
            if current_language == 'en' or current_language is None:
                current_segment += char
                current_language = 'en'
            else:
                cleaned_text += current_segment + ' '
                current_segment = char
                current_language = 'en'
        elif re.match(r'[ം-ൿ]', char):
            if current_language == 'ml' or current_language is None:
                current_segment += char
                current_language = 'ml'
            else:
                cleaned_text += current_segment + ' '
                current_segment = char
                current_language = 'ml'
        else:
            if current_segment:
                cleaned_text += current_segment + ' '
            current_segment = ""
            current_language = None

    # Add the last segment
    if current_segment:
        cleaned_text += current_segment

    return cleaned_text.strip()

from tqdm import tqdm

# Applying the function with a progress bar on a list
data = [clean_code_mixed_text(text).lower() for text in tqdm(data)]
data = pd.Series(data)
data_ub = [clean_code_mixed_text(text).lower() for text in tqdm(data_ub)]
data_ub = pd.Series(data_ub)

# Now you can use progress_apply with a progress bar
from tqdm import tqdm
tqdm.pandas()

data = data.progress_apply(clean_code_mixed_text).str.lower()
data_ub = data_ub.progress_apply(clean_code_mixed_text).str.lower()

data_ub

from torch.utils.data import Dataset, DataLoader
from tokenizers import Tokenizer
from sklearn.preprocessing import LabelEncoder
import torch

class TextDataset(Dataset):
    def __init__(self, data, labels, tokenizer, max_seq_length):
        self.data = data
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_seq_length = max_seq_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data[idx]
        label = self.labels[idx]  # Get the corresponding label
        encoding = self.tokenizer.encode(text)
        tokens = encoding.ids[:self.max_seq_length]
        padded_tokens = tokens + [0] * (self.max_seq_length - len(tokens))
        return torch.tensor(padded_tokens), torch.tensor(label)  # Return both tokens and label

encoder = LabelEncoder()
label = encoder.fit_transform(label
                              )
# Load the tokenizer
tokenizer_path = '/content/drive/MyDrive/PHD_Corpus/tokenizer.json'  # Path to your tokenizer
tokenizer = Tokenizer.from_file(tokenizer_path)


encoder_ub = LabelEncoder()
label_ub = encoder_ub.fit_transform(label_ub
                              )
# Create datasets and dataloaders
dataset = TextDataset(data, labels, tokenizer, max_seq_length=512)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# Create datasets and dataloaders
dataset_ub = TextDataset(data_ub, labels_ub, tokenizer, max_seq_length=512)
dataloader_ub = DataLoader(dataset_ub, batch_size=32, shuffle=True)

# Print the mapping of encoded labels to original label names
label_mapping = dict(zip(encoder.classes_, range(len(encoder.classes_))))
print(label_mapping)

print(dataset.data)

# Function to tokenize text using the custom tokenizer
def tokenize_text(text):
    return tokenizer.encode(text).tokens  # This returns a list of tokens

# Assuming 'df' is your DataFrame and it has a column 'Review_Text'
df['Review_text_tokens'] = df['Review_Text'].map(tokenize_text)
# Save the tokenized data to a new DataFrame
df_tokens = pd.DataFrame(df['Review_text_tokens'])
# Display the new DataFrame with tokenized text
print(df_tokens.head())
# Optionally, you can save df_tokens to a CSV if needed
df_tokens.to_csv('balanced_tokenized_reviews.csv', index=False)


# Assuming 'df' is your DataFrame and it has a column 'Review_Text'
df_ub['Review_text_tokens'] = df_ub['Review_Text'].map(tokenize_text)
# Save the tokenized data to a new DataFrame
df_tokens_ub = pd.DataFrame(df_ub['Review_text_tokens'])
# Display the new DataFrame with tokenized text
print(df_tokens_ub.head())
# Optionally, you can save df_tokens to a CSV if needed
df_tokens_ub.to_csv('unbalanced_tokenized_reviews.csv', index=False)

text_vector = df_tokens['Review_text_tokens'].tolist()
print(text_vector[:5])
text_vector_ub = df_tokens_ub['Review_text_tokens'].tolist()
print(text_vector[:5])

"""**bold text**"""

!pip install gensim

from gensim.models import Word2Vec

# Train Word2Vec model
w2v_model = Word2Vec(sentences=text_vector, vector_size=100, window=5, min_count=1, workers=4)
w2v_model_ub = Word2Vec(sentences=text_vector_ub, vector_size=100, window=5, min_count=1, workers=4)
# Accessing word vectors
word_vector = w2v_model.wv['review']  # Replace 'review' with any word in your vocabulary
print("Word vector for 'review':", word_vector)
word_vector_ub = w2v_model_ub.wv['review']  # Replace 'review' with any word in your vocabulary
print("Word vector for 'review':", word_vector_ub)

# Sentence embeddings (average word vectors for a sentence)
def get_sentence_embedding(tokens, model):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    return sum(vectors) / len(vectors) if vectors else [0] * model.vector_size

# Apply sentence embeddings for each row in the DataFrame
df_tokens['Sentence_Embedding'] = df_tokens['Review_text_tokens'].apply(
    lambda tokens: get_sentence_embedding(tokens, w2v_model)
)
# Apply sentence embeddings for each row in the DataFrame
df_tokens_ub['Sentence_Embedding'] = df_tokens_ub['Review_text_tokens'].apply(
    lambda tokens: get_sentence_embedding(tokens, w2v_model_ub)
)

print(df_tokens.head())

import numpy as np

# Convert sentence embeddings into a 2D numpy array
X = np.array(df_tokens['Sentence_Embedding'].tolist())
y = df['Sentiment_Class'].values  # Sentiment labels (0 or 1)
X_ub = np.array(df_tokens_ub['Sentence_Embedding'].tolist())
y_ub = df_ub['Sentiment_Class'].values  # Sentiment labels (0 or 1)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train_ub, X_test_ub, y_train_ub, y_test_ub = train_test_split(X_ub, y_ub, test_size=0.25, random_state=42)

# Initialize models
lr_model = LogisticRegression()
dt_model = DecisionTreeClassifier()
rf_model = RandomForestClassifier()
svm_model = SVC()

# Train Logistic Regression
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_preds)
print("Logistic Regression Accuracy:", lr_accuracy)

# Train Decision Tree
dt_model.fit(X_train, y_train)
dt_preds = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_preds)
print("Decision Tree Accuracy:", dt_accuracy)

# Train Random Forest
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_preds)
print("Random Forest Accuracy:", rf_accuracy)

# Train SVM
svm_model.fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_preds)
print("SVM Accuracy:", svm_accuracy)

# ?Train with unbalanced corpus
# Train Logistic Regression
lr_model.fit(X_train_ub, y_train_ub)
lr_preds = lr_model.predict(X_test_ub)
lr_accuracy = accuracy_score(y_test_ub, lr_preds)
print("Logistic Regression Accuracy:", lr_accuracy)

# Train Decision Tree
dt_model.fit(X_train_ub, y_train_ub)
dt_preds = dt_model.predict(X_test_ub)
dt_accuracy = accuracy_score(y_test_ub, dt_preds)
print("Decision Tree Accuracy:", dt_accuracy)

# Train Random Forest
rf_model.fit(X_train_ub, y_train_ub)
rf_preds = rf_model.predict(X_test_ub)
rf_accuracy = accuracy_score(y_test_ub, rf_preds)
print("Random Forest Accuracy:", rf_accuracy)

# Train SVM
svm_model.fit(X_train_ub, y_train_ub)
svm_preds = svm_model.predict(X_test_ub)
svm_accuracy = accuracy_score(y_test_ub, svm_preds)
print("SVM Accuracy:", svm_accuracy)

!pip install fasttext

import fasttext
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

with open('data.txt', 'w') as f:  # Saving it temporarily for training fastText
    for tokens in df_tokens['Review_text_tokens']:
        f.write(" ".join(tokens) + "\n")
# Train the fastText model on tokenized reviews (you can use pre-trained fastText model as well)
# Here, we're creating a model from scratch. Alternatively, you can use pre-trained fastText embeddings.
fasttext_model = fasttext.train_unsupervised(input='data.txt', model='skipgram')  # Using skipgram model

# Function to calculate sentence embeddings using fastText (average word embeddings)
def get_sentence_embedding(tokens, model):
    vectors = [model.get_word_vector(word) for word in tokens]
    return np.mean(vectors, axis=0) if vectors else np.zeros(model.get_dimension())

# Add sentence embeddings as a new column
df_tokens['Sentence_Embedding'] = df_tokens['Review_text_tokens'].apply(
    lambda tokens: get_sentence_embedding(tokens, fasttext_model)
)

# Convert sentence embeddings into a 2D numpy array
X = np.array(df_tokens['Sentence_Embedding'].tolist())
y = df['Sentiment_Class'].values  # Sentiment labels (0 or 1)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train_ub, X_test_ub, y_train_ub, y_test_ub = train_test_split(X_ub, y_ub, test_size=0.25, random_state=42)

# Initialize models
lr_model = LogisticRegression()
dt_model = DecisionTreeClassifier()
rf_model = RandomForestClassifier()
svm_model = SVC()

# Train Logistic Regression
lr_model.fit(X_train, y_train)
lr_preds = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_preds)
print("Logistic Regression Accuracy:", lr_accuracy)

# Train Decision Tree
dt_model.fit(X_train, y_train)
dt_preds = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_preds)
print("Decision Tree Accuracy:", dt_accuracy)

# Train Random Forest
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_preds)
print("Random Forest Accuracy:", rf_accuracy)

# Train SVM
svm_model.fit(X_train, y_train)
svm_preds = svm_model.predict(X_test)
svm_accuracy = accuracy_score(y_test, svm_preds)
print("SVM Accuracy:", svm_accuracy)


#unbalanced corpus

lr_model.fit(X_train_ub, y_train_ub)
lr_preds = lr_model.predict(X_test_ub)
lr_accuracy = accuracy_score(y_test_ub, lr_preds)
print("Logistic Regression Accuracy:", lr_accuracy)

# Train Decision Tree
dt_model.fit(X_train_ub, y_train_ub)
dt_preds = dt_model.predict(X_test_ub)
dt_accuracy = accuracy_score(y_test_ub, dt_preds)
print("Decision Tree Accuracy:", dt_accuracy)

# Train Random Forest
rf_model.fit(X_train_ub, y_train_ub)
rf_preds = rf_model.predict(X_test_ub)
rf_accuracy = accuracy_score(y_test_ub, rf_preds)
print("Random Forest Accuracy:", rf_accuracy)

# Train SVM
svm_model.fit(X_train_ub, y_train_ub)
svm_preds = svm_model.predict(X_test_ub)
svm_accuracy = accuracy_score(y_test_ub, svm_preds)
print("SVM Accuracy:", svm_accuracy)

"""******************

**************
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm

def tfid(text_vector):
    vectorizer = TfidfVectorizer()
    # Convert tokenized data back to strings (space-separated tokens)
    untokenized_data = [' '.join(tweet) for tweet in tqdm(text_vector, "Vectorizing...")]

    # Fit and transform the data using TfidfVectorizer
    vectors = vectorizer.fit_transform(untokenized_data).toarray()
    return vectors

# def tfid(text_vector):
#     vectorizer = TfidfVectorizer()
#     untokenized_data =[' '.join(tweet) for tweet in tqdm(text_vector, "Vectorizing...")]
#     vectorizer = vectorizer.fit(text_vector)
#     vectors = vectorizer.transform(text_vector).toarray()
#     return vectors

def get_vectors(vectors, labels, keyword):
    if len(vectors) != len(labels):
        print("Unmatching sizes!")
        return
    result = list()
    for vector, label in zip(vectors, labels):
        if label == keyword:
            result.append(vector)
    return result

vectors_a = tfid(text_vector) # Numerical Vectors A
labels_a = label.tolist()
vectors_a_ub = tfid(text_vector_ub) # Numerical Vectors A
labels_a_ub = label_ub.tolist()

vectors_a.shape

len(labels_a)

vectors_a_ub.shape

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils import class_weight

# Commented out IPython magic to ensure Python compatibility.
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

from sklearn.utils import compute_class_weight
from sklearn.metrics import roc_curve, roc_auc_score

def compute_class_weight_dictionary(y_train):
    # Helper for returning a dictionary instead of an array
    classes = np.unique(y_train)
    class_weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
    class_weight_dict = dict(zip(classes, class_weights))
    return class_weight_dict

def classify(vectors, labels, type="DT"):
    # Random Splitting With Ratio 3:1
    train_vectors, test_vectors, train_labels, test_labels = train_test_split(
        vectors, labels, stratify=labels, test_size=0.25, random_state=42
    )

    # Compute class weights for imbalance handling
    class_weights = compute_class_weight_dictionary(train_labels)
    print(f"Class Weights: {class_weights}")

    # Initialize Model
    classifier = None
    if type == "MNB":
        print("\nBuilding Multinomial Naive Bayes (MNB) Model...")
        classifier = MultinomialNB()

        # Grid Search for hyperparameter tuning
        param_grid = {'alpha': [0.1, 0.2, 0.5, 0.7, 1.0, 2.0, 5.0]}
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_  # Get the best model
        print(f"Best alpha: {grid_search.best_params_['alpha']}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    elif type == "KNN":
        classifier = KNeighborsClassifier(n_jobs=4)
        param_grid = {
            'n_neighbors': [3, 5, 7, 9, 11],
            'weights': ['uniform', 'distance'],
            'p': [1, 2]  # p=1 for Manhattan, p=2 for Euclidean
        }
        # GridSearchCV with cross-validation
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_
        # Print best parameters and accuracy
        print(f"Best parameters: {grid_search.best_params_}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    elif type == "SVM":
        classifier = SVC()
        # grid_search = GridSearchCV(classifier, {'C': [0.001, 0.01, 0.1, 1, 10]}, cv=5, n_jobs=4)
        # grid_search.fit(train_vectors, train_labels)
        # best_model = grid_search.best_estimator_
        # Param grid for hyperparameter tuning (including C, gamma, and kernel)
        param_grid = {
            'C': [0.001, 0.01, 0.1, 1, 10, 100],
            'gamma': ['scale', 'auto', 0.1, 0.5, 1.0],
            'kernel': ['rbf', 'linear', 'poly']
        }
        # GridSearchCV with cross-validation
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_
        # Print best parameters and accuracy
        print(f"Best parameters: {grid_search.best_params_}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    elif type == "DT":
        classifier = DecisionTreeClassifier(max_depth=800, min_samples_split=5)
        # Param grid for hyperparameter tuning (depth, criteria, and min samples)
        param_grid = {
            'criterion': ['gini', 'entropy'],
            'max_depth': [None, 5, 10, 20, 50, 100],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        }
        # GridSearchCV with cross-validation
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_
        # Print best parameters and accuracy
        print(f"Best parameters: {grid_search.best_params_}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    elif type == "LR":
        classifier = LogisticRegression(multi_class='auto', solver='newton-cg', class_weight=class_weights)
        # grid_search = GridSearchCV(classifier, {"C": np.logspace(-3, 3, 7), "penalty": ["l2"]}, cv=5, n_jobs=4)
        # grid_search.fit(train_vectors, train_labels)
        # best_model = grid_search.best_estimator_
        param_grid = {
            'C': np.logspace(-3, 3, 7),
            'penalty': ['l2'],
            'solver': ['newton-cg', 'lbfgs', 'saga']
        }
        # GridSearchCV with cross-validation
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_
        # Print best parameters and accuracy
        print(f"Best parameters: {grid_search.best_params_}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    elif type == "RF":
        classifier = RandomForestClassifier(n_estimators=100, max_depth=800, min_samples_split=5)
        # Param grid for hyperparameter tuning (depth, estimators, etc.)
        param_grid = {
            'n_estimators': [100, 200, 300],
            'max_depth': [None, 10, 50, 100],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4],
            'criterion': ['gini', 'entropy']
        }
        # GridSearchCV with cross-validation
        grid_search = GridSearchCV(estimator=classifier, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)
        grid_search.fit(train_vectors, train_labels)
        best_model = grid_search.best_estimator_
        # Print best parameters and accuracy
        print(f"Best parameters: {grid_search.best_params_}")
        print(f"Best cross-validation accuracy: {grid_search.best_score_}")

    else:
        print("Wrong Classifier Type!")
        return

    # Evaluate the model
    accuracy = accuracy_score(train_labels, best_model.predict(train_vectors))
    print("Training Accuracy:", accuracy)
    test_predictions = best_model.predict(test_vectors)
    test_accuracy = accuracy_score(test_labels, test_predictions)
    print("Test Accuracy:", test_accuracy)
    print("Confusion Matrix:")
    print(confusion_matrix(test_labels, test_predictions))
    print("Classification Report:")
    print(classification_report(test_labels, test_predictions))

# Probability predictions for ROC curve
    y_prob = best_model.predict_proba(test_vectors)
    y_pred = best_model.predict(test_vectors)

    # Plotting Accuracy
    fig, ax = plt.subplots(1, 2, figsize=(14, 6))

    # Accuracy plot
    ax[0].bar(["Train", "Test"], [accuracy, test_accuracy], color=["blue", "orange"])
    ax[0].set_title("Accuracy Comparison")
    ax[0].set_ylabel("Accuracy")



    # ROC Curve
    y_test_binary = pd.get_dummies(test_labels)  # Convert test labels to binary format
    for i, class_name in enumerate(y_test_binary.columns):
        fpr, tpr, _ = roc_curve(y_test_binary[class_name], y_prob[:, i])
        auc = roc_auc_score(y_test_binary[class_name], y_prob[:, i])
        ax[1].plot(fpr, tpr, label=f"Class {class_name} (AUC: {auc:.2f})")

    ax[1].plot([0, 1], [0, 1], 'k--')  # Diagonal line
    ax[1].set_title("ROC Curve")
    ax[1].set_xlabel("False Positive Rate")
    ax[1].set_ylabel("True Positive Rate")
    ax[1].legend(loc="best")

    plt.show()

print("\nBuilding Model MNB...")
classify(vectors_a, labels_a, "MNB")

"""**{'Mixed Feelings': 0, 'Negative': 1, 'Neutral': 2, 'Not_relevant': 3, 'Positive': 4}**"""

vectors_a_ub.shape

print("\nBuilding Model MNB...")
classify(vectors_a_ub, labels_a_ub, "MNB")

"""**{'Mixed Feelings': 0, 'Negative': 1, 'Neutral': 2, 'Not_relevant': 3, 'Positive': 4}**"""

print("\nBuilding Model LR...")
classify(vectors_a, labels_a, "LR")

print("\nBuilding Model LR...")
classify(vectors_a_ub, labels_a_ub, "LR")

print("\nBuilding Model KNN...")
classify(vectors_a, labels_a, "KNN")

"""**{'Mixed Feelings': 0, 'Negative': 1, 'Neutral': 2, 'Not_relevant': 3, 'Positive': 4}**"""

print("\nBuilding Model KNN using unbalaced corpus...")
classify(vectors_a_ub, labels_a_ub, "KNN")

print("\nBuilding Model SVM...")
classify(vectors_a, labels_a, "SVM")

print("\nBuilding Model SVM using unbalanced corpus...")
classify(vectors_a_ub, labels_a_ub, "SVM")

print("\nBuilding Model DT...")
classify(vectors_a, labels_a, "DT")

print("\nBuilding Model DT using unbalanced corpus...")
classify(vectors_a_ub, labels_a_ub, "DT")

print("\nBuilding Model RF...")
classify(vectors_a, labels_a, "RF")

print("\nBuilding Model RF using unbalanced corpus...")
classify(vectors_a_ub, labels_a_ub, "RF")

"""**bold text**

1.   List item
2.   List item


"""

from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

tv=TfidfVectorizer(ngram_range=(2,2))
tv
lr=LogisticRegression(max_iter=100000)

y=df['Sentiment_Class'].tolist()
y_ub=df_ub['Sentiment_Class'].tolist()
X_train, X_test, y_train, y_test = train_test_split(df['Review_Text'].tolist(), y, random_state=5, test_size=0.15) #train, test split
X_train_ub, X_test_ub, y_train_ub, y_test_ub = train_test_split(df_ub['Review_Text'].tolist(), y_ub, random_state=5, test_size=0.15) #train, test split

x_train=tv.fit_transform(X_train)
# train_vectors, test_vectors, train_labels, test_labels = train_test_split(vectors_a, labels, random_state=5, test_size=0.1)
# print(train_labels)#, test_vectors, train_labels, test_labels
lr.fit(x_train,y_train)
pred_1=lr.predict(tv.transform(X_test))
# print(pred_1)

from sklearn.metrics import confusion_matrix
conf=confusion_matrix(y_test, pred_1)

x_train_ub=tv.fit_transform(X_train_ub)
# train_vectors, test_vectors, train_labels, test_labels = train_test_split(vectors_a, labels, random_state=5, test_size=0.1)
# print(train_labels)#, test_vectors, train_labels, test_labels
lr.fit(x_train_ub,y_train_ub)
pred_1_ub=lr.predict(tv.transform(X_test_ub))
# print(pred_1)

from sklearn.metrics import confusion_matrix
conf=confusion_matrix(y_test_ub, pred_1_ub)

import seaborn as sn
import matplotlib.pyplot as plt
data = {'Actual':y_test,'Predicted':pred_1}
df = pd.DataFrame(data, columns=['Actual','Predicted'])
conf_matrix_table = pd.crosstab(df['Actual'], df['Predicted'], rownames=['Actual'], colnames=['Predicted'])
# sn.heatmap(conf_matrix_table, annot=True,fmt=".1f")
# plt.show()
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_1))
from sklearn.metrics import accuracy_score
score_1=accuracy_score(y_test,pred_1)
print("\nUsing Logistic Regression, Accuracy= ",score_1)

data_ub= {'Actual':y_test_ub,'Predicted':pred_1_ub}
df_ub = pd.DataFrame(data_ub, columns=['Actual','Predicted'])
conf_matrix_table_ub = pd.crosstab(df_ub['Actual'], df_ub['Predicted'], rownames=['Actual'], colnames=['Predicted'])
# sn.heatmap(conf_matrix_table, annot=True,fmt=".1f")
# plt.show()
from sklearn.metrics import classification_report
print(classification_report(y_test_ub, pred_1)_ub)
from sklearn.metrics import accuracy_score
score_1_ub=accuracy_score(y_test_ub,pred_1_ub)
print("\nUsing Logistic Regression, Accuracy= ",score_1_ub)

# data = {'y_Actual':y_test,'y_Predicted':pred_1}
# dataset = pd.DataFrame(data, columns=['y_Actual','y_Predicted'])
# conf_matrix_table = pd.crosstab(dataset['y_Actual'], dataset['y_Predicted'], rownames=['Actual'], colnames=['Predicted'])
# sn.heatmap(conf_matrix_table, annot=True,fmt=".1f")
# plt.show()

# from sklearn.metrics import accuracy_score
# score_1=accuracy_score(y_test,pred_1)
# print("\nUsing Logistic Regression, Accuracy= ",score_1)

print("\nBuilding Model SVM...")
classify(vectors_a, labels_a, "SVM") #

print("\nBuilding Model KNN...")
classify(vectors_a, labels_a, "KNN")

print("\nBuilding Model DT...")
classify(vectors_a, labels_a, "DT")

print("\nBuilding Model RF...")
classify(vectors_a, labels_a, "RF")

from sklearn import metrics
from sklearn.svm import SVC

x_train, x_test, y_train, y_test = train_test_split(vectors_a, labels_a, stratify=label,test_size=0.25, random_state=42)
x_train_ub, x_test_ub, y_train_ub, y_test_ub = train_test_split(vectors_a_ub, labels_a_ub, stratify=label_ub,test_size=0.25, random_state=42)

# model_SVM = SVC(kernel = 'poly') #rbf
# model_SVM.fit(x_train, y_train)
# y_pred_SVM = model_SVM.predict(x_test)
# print("SVM")
# print(metrics.classification_report(y_test, y_pred_SVM))

# from sklearn.ensemble import RandomForestClassifier
# rf = RandomForestClassifier()
# rf.fit(x_train,y_train)
# y_pred_rf = rf.predict(x_test)
# print("random")
# print(metrics.classification_report(y_test, y_pred_rf))

# from sklearn.linear_model import LogisticRegression
# LR = LogisticRegression()
# LR.fit(x_train,y_train)
# y_pred_LR = LR.predict(x_test)
# print("Logistic Regression")
# print(metrics.classification_report(y_test, y_pred_LR ))

# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier()
# neigh.fit(x_train,y_train)
# y_pred_KNN = neigh.predict(x_test)
# print("KNN")
# print(metrics.classification_report(y_test, y_pred_KNN ))

# from sklearn.naive_bayes import GaussianNB
# naive = GaussianNB()
# naive.fit(x_train,y_train)
# y_pred_naive = naive.predict(x_test)
# print("Naive Bayes")
# print(metrics.classification_report(y_test, y_pred_naive ))

from sklearn.ensemble import GradientBoostingClassifier
gradient = GradientBoostingClassifier()
gradient.fit(x_train,y_train)
y_pred_gradient = gradient.predict(x_test)
print("Gradient Boosting")
print(metrics.classification_report(y_test, y_pred_gradient ))

gradient.fit(x_train_ub,y_train_ub)
y_pred_gradient_ub = gradient.predict(x_test_ub)
print("Gradient Boosting_unbalanced")
print(metrics.classification_report(y_test_ub, y_pred_gradient_ub))

# from sklearn.tree import DecisionTreeClassifier
# decision = DecisionTreeClassifier()
# decision.fit(x_train,y_train)
# y_pred_decision = decision.predict(x_test)
# print("Decision Tree")
# print(metrics.classification_report(y_test, y_pred_decision ))

from sklearn.ensemble import AdaBoostClassifier
AdaBoostclf = AdaBoostClassifier()
AdaBoostclf.fit(x_train,y_train)
y_pred_AdaBoostclf = AdaBoostclf.predict(x_test)
print("AdaBoost classifier")
print(metrics.classification_report(y_test, y_pred_AdaBoostclf ))

AdaBoostclf.fit(x_train_ub,y_train_ub)
y_pred_AdaBoostclf_ub = AdaBoostclf.predict(x_test_ub)
print("AdaBoost classifier unbalanced")
print(metrics.classification_report(y_test_ub, y_pred_AdaBoostclf_ub ))

from sklearn import metrics
from sklearn.svm import SVC

x_train, x_test, y_train, y_test = train_test_split(vectors_a_ub, labels_a_ub, stratify=label,test_size=0.25, random_state=42)
print("Unbalance corpus")

model_SVM = SVC(kernel = 'poly') #rbf
model_SVM.fit(x_train, y_train)
y_pred_SVM = model_SVM.predict(x_test)
print("SVM")
print(metrics.classification_report(y_test, y_pred_SVM))

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred_rf = rf.predict(x_test)
print("random")
print(metrics.classification_report(y_test, y_pred_rf))

from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train,y_train)
y_pred_LR = LR.predict(x_test)
print("Logistic Regression")
print(metrics.classification_report(y_test, y_pred_LR ))

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()
neigh.fit(x_train,y_train)
y_pred_KNN = neigh.predict(x_test)
print("KNN")
print(metrics.classification_report(y_test, y_pred_KNN ))

from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(x_train,y_train)
y_pred_naive = naive.predict(x_test)
print("Naive Bayes")
print(metrics.classification_report(y_test, y_pred_naive ))

from sklearn.ensemble import GradientBoostingClassifier
gradient = GradientBoostingClassifier()
gradient.fit(x_train,y_train)
y_pred_gradient = gradient.predict(x_test)
print("Gradient Boosting")
print(metrics.classification_report(y_test, y_pred_gradient ))

from sklearn.tree import DecisionTreeClassifier
decision = DecisionTreeClassifier()
decision.fit(x_train,y_train)
y_pred_decision = decision.predict(x_test)
print("Decision Tree")
print(metrics.classification_report(y_test, y_pred_decision ))

from sklearn.ensemble import AdaBoostClassifier
AdaBoostclf = AdaBoostClassifier()
AdaBoostclf.fit(x_train,y_train)
y_pred_AdaBoostclf = AdaBoostclf.predict(x_test)
print("AdaBoost classifier")
print(metrics.classification_report(y_test, y_pred_AdaBoostclf ))

# from keras.utils.np_utils import to_categorical
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
class_label_train=df['Review_Text']
class_label_test=df['Sentiment_Class']
le.fit(class_label_train)
print(le.classes_)
y_train_index = le.transform(class_label_train)
#le.inverse_transform(y_train_index)
#y_dev_index = le.transform(class_label_dev)
y_test_index = le.transform(class_label_test)
label_train = to_categorical(np.asarray(y_train_index))
label_test = to_categorical(np.asarray(y_test_index))

class_final = ['Mixed Feelings ','Positive ', 'Not_relevant', 'Neutral', 'Negative ']
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp

def plot_AUC_ROC(y_true, y_pred):
    n_classes = 2

    # Compute ROC curve and ROC area for each class
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(n_classes):
        fpr[i], tpr[i], _ = roc_curve(y_true[:, i], y_pred[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    # Compute micro-average ROC curve and ROC area
    fpr["micro"], tpr["micro"], _ = roc_curve(y_true.ravel(), y_pred.ravel())
    roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])
############################################################################################
    lw = 2
    # Compute macro-average ROC curve and ROC area

    # First aggregate all false positive rates
    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

    # Then interpolate all ROC curves at this points
    mean_tpr = np.zeros_like(all_fpr)
    for i in range(n_classes):
        mean_tpr += interp(all_fpr, fpr[i], tpr[i])

    # Finally average it and compute AUC
    mean_tpr /= n_classes

    fpr["macro"] = all_fpr
    tpr["macro"] = mean_tpr
    roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

    # Plot all ROC curves
    plt.figure()

    plt.plot(fpr["micro"], tpr["micro"],
            label='micro-average ROC curve (area = {0:0.2f})'
               ''.format(roc_auc["micro"]),
            color='deeppink', linestyle=':', linewidth=4)

    plt.plot(fpr["macro"], tpr["macro"],
            label='macro-average ROC curve (area = {0:0.2f})'
               ''.format(roc_auc["macro"]),
            color='navy', linestyle=':', linewidth=4)

    colors = cycle(['aqua', 'darkorange', 'cornflowerblue'])
    #classes_list1 = ["DE","NE","DK"]
    classes_list1 = class_final
    for i, color,c in zip(range(n_classes), colors,classes_list1):
        plt.plot(fpr[i], tpr[i], color=color, lw=lw,
                label='{0} (AUC = {1:0.2f})'
                ''.format(c, roc_auc[i]))

    plt.plot([0, 1], [0, 1], 'k--', lw=lw)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic curve')
    plt.legend(loc="lower right")
    #plt.show()

    # Plot of a ROC curve for a specific class
    '''
    plt.figure()
    lw = 2
    plt.plot(fpr[0], tpr[0], color='darkorange',
            lw=lw, label='ROC curve (area = %0.2f)' % roc_auc[0])
    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    plt.show()
    '''

plot_AUC_ROC(label_test,y_pred_LR_prob)